/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class Bar10 {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Bar10(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Bar10 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        swigtest1JNI.delete_Bar10(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setY(int value) {
    swigtest1JNI.Bar10_y_set(swigCPtr, this, value);
  }

  public int getY() {
    return swigtest1JNI.Bar10_y_get(swigCPtr, this);
  }

  public Bar10() {
    this(swigtest1JNI.new_Bar10(), true);
  }

}
