/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class swigtest1JNI {
  public final static native int foo10(int jarg1);
  public final static native void Bar10_y_set(long jarg1, Bar10 jarg1_, int jarg2);
  public final static native int Bar10_y_get(long jarg1, Bar10 jarg1_);
  public final static native long new_Bar10();
  public final static native void delete_Bar10(long jarg1);
}
